---
include:
  - board: nice_nano
    shield: keyball39_left nice_view_adapter nice_view
  - board: nice_nano
    shield: keyball39_right nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: settings_reset
